// Objective-C API for talking to github.com/NightBlaze/GomobileDemo/engine Go package.
//   gobind -lang=objc github.com/NightBlaze/GomobileDemo/engine
//
// File is generated by gobind. Do not edit.

#ifndef __Engine_H__
#define __Engine_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class EngineLogic;
@protocol EngineDelegate;
@class EngineDelegate;

@protocol EngineDelegate <NSObject>
- (void)done:(long)p0;
@end

@interface EngineLogic : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(id<EngineDelegate> _Nullable)delegate;
- (void)executeJob:(long)job;
- (void)free;
@end

FOUNDATION_EXPORT EngineLogic* _Nullable EngineNewLogic(id<EngineDelegate> _Nullable delegate);

@class EngineDelegate;

@interface EngineDelegate : NSObject <goSeqRefInterface, EngineDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)done:(long)p0;
@end

#endif
