
// Objective-C API for talking to the following Go packages
//
//	github.com/NightBlaze/GomobileDemo/engine
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Engine_FRAMEWORK_H__
#define __Engine_FRAMEWORK_H__

#include "Engine.objc.h"
#include "Universe.objc.h"

#endif
